[package]
name = "xlsx2sql"
version = "0.1.5"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
calamine = "0.25"
thiserror = "1.0"
anyhow = "1.0"
chrono = "0.4.41"
dialoguer = "0.11.0"

[dev-dependencies]
tempfile = "3.0"
